### ISSUE TITLE
Request for transparent integration of object transfers

### ISSUE THREAD

**Issue by eliadl** [eplaut/python-butler#9]
An existing use case with current (or future) Butler code:
1.` myButlerClient.post_update_func(json.dumps(myObject))`
2. `myObject = json.loads(flask.request.data)` @ `myButlerServer.post_update_func`

If butler was meant to spare usages of flask, json, etc. perhaps it would be wise to integrate this use case as well.

**Comment by eliadl** [comment]
Another use case is passing arguments:
1. `myButlerClient.post_update_func2(name="John")`
2. `name = flask.request.args['name']` @ `myButlerServer.post_update_func2`

**Comment by eplaut** [comment]
#12 fix this.
Butler has `json` and `params` properties to handle `request.data` and `request.args`
